apiVersion: v1
kind: Deplyoment
metadata:
    name: backend-blue
    namespace: expense
    #labels of deplyoment  resource
    labels:
       app: backend
       tier: backend
       project: expense
       version: blue

    spec:
       replice: 1
       selector:
          matchlabels: 
             app: backend
             tier: backend
             project: expense
             version: blue
          template:
             metadata:
                labels:
                   app: backend
                   tier: backend
                   project: expense
                   version: blue

             spec: 
               containers:
               - name: nginx
                 image: shashanka00315964/backend:3.0.0 
                 envfrom:
                  - configMapRef: 
                      name: backend        