apiVersion: v1
kind: Deplyoment
metadata: 
  name: backend-green
  namespace: expense
  # labels of deplyoment resource
  labels:
    app: backend
    tier: backend
    project: expense
    version: green
  spec: 
  replice: 1
  selector:
  matchlabels:
  app: backend
  tier: backend
  project: expense
  version: green
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
        version: green
    spec:
      containers:
      - name: nginx
        image: shashanka00315964/backend:2.0.0
        envFrom:
        - configMapRef:
            name: backend
    